# Generated by Django 4.2 on 2026-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=100)),
                ('student_lastname', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_national_id', models.BigIntegerField()),
                ('student_phone', models.BigIntegerField()),
                ('student_address', models.CharField(max_length=255)),
                ('primary_school', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_school', models.CharField(blank=True, max_length=150, null=True)),
                ('father_firstname', models.CharField(max_length=100)),
                ('father_lastname', models.CharField(max_length=100)),
                ('father_phone', models.BigIntegerField()),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_national_id', models.BigIntegerField(blank=True, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_firstname', models.CharField(max_length=100)),
                ('mother_lastname', models.CharField(max_length=100)),
                ('mother_phone', models.BigIntegerField()),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_national_id', models.BigIntegerField(blank=True, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
