# Generated by Django 4.2 on 2026-02-06 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_firstname', models.CharField(max_length=100)),
                ('student_lastname', models.CharField(max_length=100)),
                ('student_class', models.CharField(choices=[('S1', 'Senior 1'), ('S2', 'Senior 2'), ('S3', 'Senior 3'), ('S4', 'Senior 4'), ('S5', 'Senior 5'), ('S6', 'Senior 6')], default='S1', max_length=2)),
                ('student_dob', models.DateField()),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('student_national_id', models.BigIntegerField(unique=True)),
                ('student_phone', models.BigIntegerField()),
                ('student_address', models.CharField(max_length=255)),
                ('primary_school', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_school', models.CharField(blank=True, max_length=150, null=True)),
                ('father_firstname', models.CharField(max_length=100)),
                ('father_lastname', models.CharField(max_length=100)),
                ('father_phone', models.BigIntegerField()),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_national_id', models.BigIntegerField(blank=True, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_firstname', models.CharField(max_length=100)),
                ('mother_lastname', models.CharField(max_length=100)),
                ('mother_phone', models.BigIntegerField()),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_national_id', models.BigIntegerField(blank=True, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('student_code', models.CharField(editable=False, max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('total_marks', models.FloatField()),
                ('mark_type', models.CharField(choices=[('Quiz', 'Quiz'), ('Exam', 'Exam')], default='Exam', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_register.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_register.teacher')),
            ],
        ),
    ]
