# Generated by Django 4.2 on 2026-02-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('S1', 'Senior 1'), ('S2', 'Senior 2'), ('S3', 'Senior 3'), ('S4', 'Senior 4'), ('S5', 'Senior 5'), ('S6', 'Senior 6')], default='S1', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_national_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
